name: MiniWDL linter CI

on:
  pull_request:
    branches: master

jobs:
  run-miniwdl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # specify the Python version you need

    - name: Install MiniWDL
      run: |
        python -m pip install --upgrade pip
        pip install miniwdl

    - name: Run MiniWDL
      run: |
        # Add the commands to run your MiniWDL workflow
        miniwdl check --no-quant-check --suppress CommandShellCheck  wdl/workflow/main.wdl
