name: Create issues in project board based on labels

on:
  issues:
    types: [opened, labeled, edited]

jobs:
  add_to_project:
    uses: microbiomedata/common/.github/workflows/project_labels.yml@main
    
